{{- with .Values.detectionAggregator }}
{{- if .enabled }}
{{- with .settingsYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: detection-aggregator-config
data:
  settings.yaml: |
    {{- toYaml . | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}