{{- with .Values.detectionSampler }}
{{- if .enabled }}
{{- range .instances }}
{{- $instanceName := printf "detection-sampler-%s" (lower .name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $instanceName }}-config
data:
  settings.yaml: |
    {{- toYaml .settingsYaml | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
