{{- with .Values.objectDetector }}
{{- $imageRepo := required "image repository for object-detector is required" .image.repository }}
{{- $imageTag := required "image tag for object-detector is required" .image.tag }}
{{- $isUsingGpu := hasPrefix "cuda" .config.model.device }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sae.fullname" $ }}-object-detector
  labels:
    {{- include "sae.labels" $ | nindent 4 }}
    app.kubernetes.io/component: object-detector
spec:
  selector:
    matchLabels:
      {{- include "sae.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: object-detector
  template:
    metadata:
      annotations:
        sae.starwit.de/stage: object-detector
        sae.starwit.de/config-checksum: {{ include (print $.Template.BasePath "/object-detector.configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "sae.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: object-detector
    spec:
      serviceAccountName: {{ include "sae.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- if $isUsingGpu }}
      runtimeClassName: nvidia
      {{- end }}
      initContainers:
        - name: wait-for-redis
          image: valkey/valkey:7.2.6-alpine
          command: ["sh", "-c", "while ! redis-cli -h {{ include "sae.redisServiceName" $ }} ping ; do echo \"$(date -Iseconds) - still waiting for redis\"; sleep 1; done"]
        {{- if .customWeights.enabled }}
        - name: install-model-weights
          image: starwitorg/sae-object-detector-weights:{{ .customWeights.imageTag }}
          volumeMounts:
            - name: custom-weights
              mountPath: /weights_target
        {{- end }}
      containers:
        - name: object-detector
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          imagePullPolicy: IfNotPresent
          {{- if $isUsingGpu }}
          resources:
            limits:
              nvidia.com/gpu: 1
          {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ .logLevel | quote }}
            - name: REDIS__HOST
              value: {{ include "sae.redisServiceName" $ }}
            - name: REDIS__PORT
              value: {{ include "sae.redisServicePort" $ }}
          ports:
            - name: prometheus
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /code/settings.yaml
              subPath: settings.yaml
            - name: custom-weights
              mountPath: /code/custom_weights
      volumes:
        - name: config
          configMap:
            name: object-detector-config
        - name: custom-weights
          emptyDir: {}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
