{{- with .Values.objectTracker }}
{{- $imageRepo := required "image repository for object-tracker is required" .image.repository }}
{{- $imageTag := required "image tag for object-tracker is required" .image.tag }}
{{- range .configs }}
{{- $isUsingGpu := hasPrefix "cuda" .device }}
{{- $instanceName := printf "object-tracker-%s" (lower .streamId) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sae.fullname" $ }}-{{ $instanceName }}
  labels:
    {{- include "sae.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $instanceName }}
spec:
  selector:
    matchLabels:
      {{- include "sae.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $instanceName }}
  template:
    metadata:
      annotations:
        sae.starwit.de/stage: object-tracker
      labels:
        {{- include "sae.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $instanceName }}
    spec:
      serviceAccountName: {{ include "sae.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- if $isUsingGpu }}
      runtimeClassName: nvidia
      {{- end }}
      initContainers:
        - name: wait-for-redis
          image: redis:7.2-alpine
          command: ["sh", "-c", "while ! redis-cli -h {{ include "sae.redisServiceName" $ }} ping ; do echo \"$(date -Iseconds) - still waiting for redis\"; sleep 1; done"]
      containers:
        - name: {{ $instanceName }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          imagePullPolicy: IfNotPresent
          {{- if $isUsingGpu }}
          resources:
            limits:
              nvidia.com/gpu: 1
          {{- end }}
          env:
            - name: TRACKING_PARAMS__DET_THRESH
              value: {{ .trackingParams.detThresh | quote }}
            - name: TRACKING_PARAMS__MODEL_WEIGHTS
              value: {{ .trackingParams.modelWeights | quote }}
            - name: DEVICE
              value: {{ .device | quote }}
            - name: LOG_LEVEL
              value: {{ .logLevel | quote }}
            - name: REDIS__HOST
              value: {{ include "sae.redisServiceName" $ }}
            - name: REDIS__PORT
              value: {{ include "sae.redisServicePort" $ }}
            - name: REDIS__STREAM_ID
              value: {{ .streamId | quote }}
          ports:
            - name: prometheus
              containerPort: 8000
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
