{{- with .Values.positionSource }}
{{- if .enabled }}
{{- $imageRepo := required "image repository for position-source is required" .image.repository }}
{{- $imageTag := required "image tag for position-source is required" .image.tag }}
{{- $rootConfig := . }}
{{- with .settingsYaml -}}
{{- $instanceName := printf "position-source" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sae.fullname" $ }}-{{ $instanceName }}
  labels:
    {{- include "sae.labels" $ | nindent 4 }}
    app.kubernetes.io/component: position-source
spec:
  selector:
    matchLabels:
      {{- include "sae.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $instanceName }}
  template:
    metadata:
      annotations:
        sae.starwit.de/stage: position-source
        sae.starwit.de/config-checksum: {{ include (print $.Template.BasePath "/position-source.configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "sae.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $instanceName }}
    spec:
      serviceAccountName: {{ include "sae.serviceAccountName" $ }}
      initContainers:
        - name: wait-for-redis
          image: valkey/valkey:7.2.6-alpine
          command: ["sh", "-c", "while ! redis-cli -h {{ include "sae.redisServiceName" $ }} ping ; do echo \"$(date -Iseconds) - still waiting for redis\"; sleep 1; done"]
      containers:
        {{- with $rootConfig.gpsdSidecar }}
        {{- if .enabled }}
        - name: gpsd
          securityContext:
            privileged: true
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: gps-device
              mountPath: /dev/gps
            - name: gpsd-config
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
        {{- end }}
        {{- end }}
        - name: {{ $instanceName }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: REDIS__HOST
              value: {{ include "sae.redisServiceName" $ }}
            - name: REDIS__PORT
              value: {{ include "sae.redisServicePort" $ }}
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: prometheus
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /code/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: config
          configMap:
            name: {{ $instanceName }}-config
        {{- with $rootConfig.gpsdSidecar }}
        {{- if .enabled }}
        - name: gps-device
          hostPath:
            path: {{ .hostGpsDevice }}
            type: CharDevice
        - name: gpsd-config
          configMap:
            name: {{ $instanceName }}-gpsd-config
        {{- end }}
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
