{{- with .Values.positionSource }}
{{- if .enabled }}
{{- with .settingsYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: position-source-config
data:
  settings.yaml: |
    {{- toYaml . | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}