name: sae

services:
  redis:
    image: valkey/valkey:7.2.6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "[ \"$(redis-cli ping)\" = \"PONG\" ] && exit 0 || exit 1"
      interval: 1s
      start_period: 5s

  position-source:
    image: ${IMAGE_REGISTRY}/sae-position-source:${POSITION_SOURCE_VERSION}
    volumes:
      - ./position-source/position-source.settings.yaml:/code/settings.yaml
      - /tmp/gps-simulator:/dev/ttyACM0
    depends_on:
      redis:
        condition: service_healthy

  video-source-stream1:
    image: ${IMAGE_REGISTRY}/sae-video-source-py:${VIDEO_SOURCE_VERSION}
    volumes:
      - ./video-source-py/video-source-stream1.settings.yaml:/code/settings.yaml
    depends_on:
      redis:
        condition: service_healthy

  object-detector:
    image: ${IMAGE_REGISTRY}/object-detector:${OBJECT_DETECTOR_VERSION}
    volumes:
      - ./object-detector/object-detector.settings.yaml:/code/settings.yaml
      - /home/anett/git/waste-detection/runs/taco-uavvaste-50-epochs-1280/best.pt:/code/yolov8n.pt
    depends_on:
      redis:
        condition: service_healthy

  # object-tracker-stream1:
  #   image: ${IMAGE_REGISTRY}/sae-object-tracker:${OBJECT_TRACKER_VERSION}
  #   volumes:
  #     - ./object-tracker/object-tracker-stream1.settings.yaml:/code/settings.yaml
  #   depends_on:
  #     redis:
  #       condition: service_healthy

  streaming-server:
    image: bluenviron/mediamtx:1.0.0-ffmpeg
    volumes:
      - ./streaming-server/mediamtx.yml:/mediamtx.yml
      - ${VIDEO_PATH}:/video
    environment:
      MTX_PROTOCOLS: tcp
    ports:
      - 8554:8554

  geo-mapper:
    image: ${IMAGE_REGISTRY}/sae-geo-mapper:${GEO_MAPPER_VERSION}
    volumes:
      - ./geo-mapper/geo-mapper.settings.yaml:/code/settings.yaml
    depends_on:
      redis:
        condition: service_healthy

  # redis-insight:
  #   image: redis/redisinsight:latest
  #   volumes:
  #     - redisinsight:/data
  #   ports:
  #     - 5540:5540

volumes:
  redisinsight:

networks:
  default:
    name: sae