include:
  - docker-compose.yml

name: sae

services:
  redis-writer:
    image: ${IMAGE_REGISTRY}/sae-redis-writer:${REDIS_WRITER_VERSION}
    volumes:
      - ./redis-writer/redis-writer.settings.yaml:/code/settings.yaml
      - ./redis-writer/certs/:/code/certs/
    depends_on:
      valkey:
        condition: service_healthy
  
  secondary-valkey:
    image: valkey/valkey:7.2.6
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    ports:
      - 16379:6379
      - 16380:6380
    volumes:
      - ./secondary-valkey/secondary-valkey.conf:/usr/local/etc/valkey/valkey.conf
      - ./secondary-valkey/certs/:/certs/
  
