version: "3.8"

include:
  - docker-compose.yml

services:
  database-writer:
    image: ${IMAGE_REGISTRY}/sae-database-writer:${DATABASE_WRITER_VERSION}
    volumes:
      - ./database-writer/.env:/app/.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin/servers-config.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy