version: '3.8'

services:
  redis:
    image: redis:7.0
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "[ \"$(redis-cli ping)\" = \"PONG\" ] && exit 0 || exit 1"
      interval: 1s
      start_period: 5s

  video-source-stream1:
    image: ${IMAGE_REGISTRY}/sae/video-source-py:${VIDEO_SOURCE_VERSION}
    volumes:
      - ./video-source-py/video-source-stream1.settings.yaml:/code/settings.yaml
    depends_on:
      redis:
        condition: service_healthy

  object-detector:
    image: ${IMAGE_REGISTRY}/sae/object-detector:${OBJECT_DETECTOR_VERSION}
    volumes:
      - ./object-detector/object-detector.settings.yaml:/code/settings.yaml
    depends_on:
      redis:
        condition: service_healthy

  object-tracker-stream1:
    image: ${IMAGE_REGISTRY}/sae/object-tracker:${OBJECT_TRACKER_VERSION}
    volumes:
      - ./object-tracker/object-tracker-stream1.settings.yaml:/code/settings.yaml
    depends_on:
      redis:
        condition: service_healthy

  streaming-server:
    image: bluenviron/mediamtx:1.0.0-ffmpeg
    volumes:
      - ./streaming-server/mediamtx.yml:/mediamtx.yml
      - /home/hanna/workspaces/anomaly_detection/test.mp4:/video_1080
      - /home/florian/workspaces/carmel/videos/RangelineSMedicalDr.mp4:/video_4k
    environment:
      MTX_PROTOCOLS: tcp
    ports:
      - 8554:8554