tracker_algorithm: OCSORT
tracker_config:
  det_thresh: 0.2
  max_age: 30
  min_hits: 3
  asso_threshold: 0.3
  delta_t: 3
  asso_func: 'iou'
  inertia: 0.2
  use_byte: False

log_level: DEBUG
redis:
  host: valkey
  port: 6379
  stream_id: stream1