{
 "title": "SAE Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "streamId", "label": "Stream-ID", "query": { "query": "label_values(pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Frame throughput per stage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(video_source_frame_counter_total[30s])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(object_detector_frame_counter_total[30s])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(object_tracker_frame_counter_total[30s])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(geo_mapper_frame_counter_total[30s])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(redis_writer_frame_counter_total[30s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "object-detector loop times (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(object_detector_proto_deserialization_duration_sum[30s])/rate(object_detector_proto_deserialization_duration_count[30s])",
     "legendFormat": "proto_deserialize()"
    },
    {
     "expr": "rate(object_detector_model_duration_sum[30s])/rate(object_detector_model_duration_count[30s])+rate(object_detector_nms_duration_sum[30s])/rate(object_detector_nms_duration_count[30s])",
     "legendFormat": "model()"
    },
    {
     "expr": "rate(object_detector_proto_serialization_duration_sum[30s])/rate(object_detector_proto_serialization_duration_count[30s])",
     "legendFormat": "proto_serialize()"
    },
    {
     "expr": "rate(object_detector_redis_publish_duration_sum[30s])/rate(object_detector_redis_publish_duration_count[30s])",
     "legendFormat": "publish()"
    }
   ]
  },
  {
   "title": "video-source loop times (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(video_source_proto_serialization_duration_sum{pod=~\".*-video-source-$streamId-0\"}[30s])/rate(video_source_proto_serialization_duration_count{pod=~\".*-video-source-$streamId-0\"}[30s])",
     "legendFormat": "proto_serialize()"
    },
    {
     "expr": "rate(video_source_redis_publish_duration_sum{pod=~\".*-video-source-$streamId-0\"}[30s])/rate(video_source_redis_publish_duration_count{pod=~\".*-video-source-$streamId-0\"}[30s])",
     "legendFormat": "publish()"
    },
    {
     "expr": "rate(video_source_wait_next_frame_duration_sum{pod=~\".*-video-source-$streamId-0\"}[30s])/rate(video_source_wait_next_frame_duration_count{pod=~\".*-video-source-$streamId-0\"}[30s])",
     "legendFormat": "wait_next_frame()"
    }
   ]
  },
  {
   "title": "object-tracker loop times (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(object_tracker_proto_deserialization_duration_sum{pod=~\".*-object-tracker-$streamId-0\"}[30s])/rate(object_tracker_proto_deserialization_duration_count{pod=~\".*-object-tracker-$streamId-0\"}[30s])",
     "legendFormat": "proto_deserialize()"
    },
    {
     "expr": "rate(object_tracker_tracker_update_duration_sum{pod=~\".*-object-tracker-$streamId-0\"}[30s])/rate(object_tracker_tracker_update_duration_count{pod=~\".*-object-tracker-$streamId-0\"}[30s])",
     "legendFormat": "tracker_update()"
    },
    {
     "expr": "rate(object_tracker_proto_serialization_duration_sum{pod=~\".*-object-tracker-$streamId-0\"}[30s])/rate(object_tracker_proto_serialization_duration_count{pod=~\".*-object-tracker-$streamId-0\"}[30s])",
     "legendFormat": "proto_serialize()"
    },
    {
     "expr": "rate(object_tracker_redis_publish_duration_sum{pod=~\".*-object-tracker-$streamId-0\"}[30s])/rate(object_tracker_redis_publish_duration_count{pod=~\".*-object-tracker-$streamId-0\"}[30s])",
     "legendFormat": "publish()"
    }
   ]
  },
  {
   "title": "video source time to next frame (from camera)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(frame_grabber_loop_duration_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}