{
 "title": "Video_Source",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pod",
    "query": {
     "query": "label_values(video_source_frame_counter_total,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Retrieved frames stream vs. picked up frames",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(video_source_frame_counter_total[30s])",
     "legendFormat": "fps ingested into pipeline"
    },
    {
     "expr": "rate(frame_grabber_frame_counter_total[30s])",
     "legendFormat": "fps retrieved from stream"
    }
   ]
  },
  {
   "title": "video_source_redis_publish_duration",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(video_source_redis_publish_duration_bucket[30s])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "video_source_redis_publish_duration_average",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(video_source_redis_publish_duration_sum[30s])/rate(video_source_redis_publish_duration_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}