version: '3.8'

services:
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
  
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  video-source-1:
    image: ${IMAGE_REGISTRY}/sae/video-source-py:${IMAGE_VERSION}
    volumes:
      - /home/florian/workspaces/carmel/videos/RangelineSMedicalDr.mp4:/video
      - ./video-source-py/video-source-1.settings.yaml:/code/settings.yaml

  video-source-2:
    image: ${IMAGE_REGISTRY}/sae/video-source-py:${IMAGE_VERSION}
    volumes:
      - /home/florian/workspaces/carmel/videos/ArchWestMainStreetEB.mp4:/video
      - ./video-source-py/video-source-2.settings.yaml:/code/settings.yaml

  video-source-stream:
    image: ${IMAGE_REGISTRY}/sae/video-source-py:${IMAGE_VERSION}
    volumes:
      - ./video-source-py/video-source-stream.settings.yaml:/code/settings.yaml

  object-detector:
    image: ${IMAGE_REGISTRY}/sae/object-detector:${IMAGE_VERSION}
    volumes:
      - ./object-detector/object-detector.settings.yaml:/code/settings.yaml

  object-tracker-1:
    image: ${IMAGE_REGISTRY}/sae/object-tracker:${IMAGE_VERSION}
    volumes:
      - ./object-tracker/object-tracker-1.settings.yaml:/code/settings.yaml

  object-tracker-2:
    image: ${IMAGE_REGISTRY}/sae/object-tracker:${IMAGE_VERSION}
    volumes:
      - ./object-tracker/object-tracker-2.settings.yaml:/code/settings.yaml

  streaming-server:
    image: bluenviron/mediamtx:1.0.0-ffmpeg
    volumes:
      - ./streaming-server/mediamtx.yml:/mediamtx.yml
      - /home/florian/workspaces/carmel/videos/ArchWestMainStreetEB.mp4:/video
    environment:
      MTX_PROTOCOLS: tcp
    ports:
      - 8554:8554

  anomaly-detector:
    image: ${IMAGE_REGISTRY}/sae/anomaly-detector:1.0-SNAPSHOT
    volumes:
      - ./anomaly-detector/anomaly-detector.settings.yaml:/code/settings.yaml