name: Release SAE chart
on:
  push:
    # branches:
    #   - main
jobs:
  ReleaseSAEChart:
    runs-on: 
      labels: infra
    container:
      image: docker.internal.starwit-infra.de/helm-build:0.1.0
      credentials:
        username: docker
        password: ${{ secrets.STARWIT_INTERNAL_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and release helm chart
        run: ./helm/do_release.sh
